# Site settings
title: GIS520 Course Portfolio
email: royhewitt07@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Roy Hewitt's GIS 520 course portfolio.  This course is part of the
  North Carolina State University GIS & Technology Masters Program/Certificate
baseurl: "" # the subpath of your site, e.g. /blog/

twitter_username: r0yhewitt
github_username:  rhewitt22

gems:
 - compass
 - susy
 - breakpoint

# Build settings
markdown: kramdown

highlighter: rouge
