# Site settings
title: GIS 520 Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Roy Hewitt's GIS 520 Course Portfolio as part of the NC State
  Master's in GIS & Technology Certificate Program
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://royhewitt.com" # the base hostname & protocol for your site

email: royhewitt07@gmail.com
twitter_username: r0yhewitt
github_username:  rhewitt22

highlighter: rouge

# Build settings
markdown: kramdown
